version: 2
updates:
- package-ecosystem: npm
  directory: "/deps-stable"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
