name: CI

on: [pull_request]

jobs:
  build-and-run-checks:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: ./build-all.sh
