name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: ./build-all.sh

      - name: Release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./push.sh
